### ISSUE TITLE
Staff?

### ISSUE THREAD

**Issue by Will-radiodisney** [vmkrewritten/website#3]
Can I be staff with Sasha?

**Comment by simcitynsun** [comment]
hmmm

**Comment by simcitynsun** [comment]
if you will be staff u will need a profile picture

**Comment by CaptVJ** [comment]
will radiodisney shouldn't be staff because he's impersonating radiodisney and impersionalt is unallowed in vmk rewritten

**Comment by simcitynsun** [comment]
radiodisney is his name hon

**Comment by CaptVJ** [comment]
> radiodisney is his name hon

oh my apolocheese

**Comment by Will-radiodisney** [comment]
Profile picture activated

**Comment by simcitynsun** [comment]
really nice photo! you look very familiar

**Comment by simcitynsun** [comment]
not sur why u closed but ur staff now ❤️  @Will-radiodisney
