### ISSUE TITLE
guest book

### ISSUE THREAD

**Issue by CaptVJ** [vmkrewritten/website#4]
i think adding a guest book to the home page to see who visits the page would be very fun and delight

**Comment by simcitynsun** [comment]
hi thanks for this idea can you make a sketch of what it would look like
@CaptVJ

**Comment by CaptVJ** [comment]
> hi thanks for this idea can you make a sketch of what it would look like @CaptVJ

hi here you go please enjoy
![image](https://github.com/vmkrewritten/website/assets/60113647/18ff12f1-b61a-4d87-b07e-0e0074c99b25)

**Comment by simcitynsun** [comment]
> > hi thanks for this idea can you make a sketch of what it would look like @CaptVJ
> 
> hi here you go please enjoy ![image](https://user-images.githubusercontent.com/60113647/274054559-18ff12f1-b61a-4d87-b07e-0e0074c99b25.png)

thank you for the design, i will try to work on it soon or someone else can make a PR if they want

**Comment by simcitynsun** [comment]
clso
